import type { Metadata } from "next";
import { Source_Serif_4, PT_Sans } from "next/font/google";
import Navbar from "@/src/components/Navbar";

import "./globals.css";
import { Providers } from "./providers";

const sourceSerif = Source_Serif_4({
  subsets: ["latin"],
  display: "swap",
});

const ptSans = PT_Sans({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="sv" className={`${sourceSerif.className} ${ptSans.className} bg-neutral-light`}>
      <body className="bg-neutral-light">
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
